// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJNlzO1Nlmsuc8WJeHD6N5_nhLOAryLe4',
    appId: '1:90003568496:web:8332839f274158285501b5',
    messagingSenderId: '90003568496',
    projectId: 'chatprototyp',
    authDomain: 'chatprototyp.firebaseapp.com',
    storageBucket: 'chatprototyp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmH50FgN_8kJCvMM4ZkG9u6MtaX6VsfxI',
    appId: '1:90003568496:android:0b610ed1a360c47d5501b5',
    messagingSenderId: '90003568496',
    projectId: 'chatprototyp',
    storageBucket: 'chatprototyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw8HtDEXpQqrMDGhd0BG25LDZuGtXrHCw',
    appId: '1:90003568496:ios:c0d17ceddabb81fa5501b5',
    messagingSenderId: '90003568496',
    projectId: 'chatprototyp',
    storageBucket: 'chatprototyp.appspot.com',
    iosBundleId: 'com.example.chattTest',
  );
}
