// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVRxQYOVOfjDY-BjQerDVeMfj1XnQ4wXg',
    appId: '1:402397254602:web:b06d61cc8ad3dc03047533',
    messagingSenderId: '402397254602',
    projectId: 'chatwithfirebase-acc3c',
    authDomain: 'chatwithfirebase-acc3c.firebaseapp.com',
    storageBucket: 'chatwithfirebase-acc3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ-csWFHKF4m9vZTYP9BpTZLmRGPt91sQ',
    appId: '1:402397254602:android:b0a602ff161cf39a047533',
    messagingSenderId: '402397254602',
    projectId: 'chatwithfirebase-acc3c',
    storageBucket: 'chatwithfirebase-acc3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiL9m_DTUdC9gRxFyVI1wCL-ZhQCEgMoY',
    appId: '1:402397254602:ios:49df25968661964b047533',
    messagingSenderId: '402397254602',
    projectId: 'chatwithfirebase-acc3c',
    storageBucket: 'chatwithfirebase-acc3c.appspot.com',
    iosBundleId: 'com.mycompany.diplomprojekt',
  );
}
